INSERT INTO EMPLOYEE VALUES(101,25,'PROG','RAJEEV');
INSERT INTO EMPLOYEE VALUES(102,27,'PROG','RAJEEVV');
INSERT INTO EMPLOYEE VALUES(103,35,'PROG','RAJEEVVV');
INSERT INTO EMPLOYEE VALUES(104,26,'PROG','RAJEEVVVV');
INSERT INTO EMPLOYEE VALUES(105,27,'PROG','RAJEEVVVV');